apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  restartPolicy: OnFailure
  containers:
    - command:
        - docker-entrypoint.sh
        - postgres
      env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/13/bin
        - name: TERM
          value: xterm
        - name: container
          value: podman
        - name: PG_VERSION
          value: 13.0-1.pgdg100+1
        - name: PGDATA
          value: /var/lib/postgresql/data
        - name: PG_MAJOR
          value: "13"
        - name: LANG
          value: en_US.utf8
        - name: GOSU_VERSION
          value: "1.12"
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: containers
          value: podman
        - name: HOSTNAME
          value: commonpool-dev
      image: docker.io/library/postgres:latest
      name: postgres
      ports:
        - containerPort: 5432
          hostPort: 5432
          protocol: TCP