// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"github.com/commonpool/backend/pkg/mq"
	"sync"
)

// Ensure, that AmqpClient does implement mq.Client.
// If this is not the case, regenerate this file with moq.
var _ mq.Client = &AmqpClient{}

// AmqpClient is a mock implementation of mq.Client.
//
//     func TestSomethingThatUsesClient(t *testing.T) {
//
//         // make and configure a mocked mq.Client
//         mockedClient := &AmqpClient{
//             GetChannelFunc: func() (mq.Channel, error) {
// 	               panic("mock out the GetChannel method")
//             },
//             ShutdownFunc: func() error {
// 	               panic("mock out the Shutdown method")
//             },
//         }
//
//         // use mockedClient in code that requires mq.Client
//         // and then make assertions.
//
//     }
type AmqpClient struct {
	// GetChannelFunc mocks the GetChannel method.
	GetChannelFunc func() (mq.Channel, error)

	// ShutdownFunc mocks the Shutdown method.
	ShutdownFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// GetChannel holds details about calls to the GetChannel method.
		GetChannel []struct {
		}
		// Shutdown holds details about calls to the Shutdown method.
		Shutdown []struct {
		}
	}
	lockGetChannel sync.RWMutex
	lockShutdown   sync.RWMutex
}

// GetChannel calls GetChannelFunc.
func (mock *AmqpClient) GetChannel() (mq.Channel, error) {
	if mock.GetChannelFunc == nil {
		panic("AmqpClient.GetChannelFunc: method is nil but Client.GetChannel was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetChannel.Lock()
	mock.calls.GetChannel = append(mock.calls.GetChannel, callInfo)
	mock.lockGetChannel.Unlock()
	return mock.GetChannelFunc()
}

// GetChannelCalls gets all the calls that were made to GetChannel.
// Check the length with:
//     len(mockedClient.GetChannelCalls())
func (mock *AmqpClient) GetChannelCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetChannel.RLock()
	calls = mock.calls.GetChannel
	mock.lockGetChannel.RUnlock()
	return calls
}

// Shutdown calls ShutdownFunc.
func (mock *AmqpClient) Shutdown() error {
	if mock.ShutdownFunc == nil {
		panic("AmqpClient.ShutdownFunc: method is nil but Client.Shutdown was just called")
	}
	callInfo := struct {
	}{}
	mock.lockShutdown.Lock()
	mock.calls.Shutdown = append(mock.calls.Shutdown, callInfo)
	mock.lockShutdown.Unlock()
	return mock.ShutdownFunc()
}

// ShutdownCalls gets all the calls that were made to Shutdown.
// Check the length with:
//     len(mockedClient.ShutdownCalls())
func (mock *AmqpClient) ShutdownCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockShutdown.RLock()
	calls = mock.calls.Shutdown
	mock.lockShutdown.RUnlock()
	return calls
}
