apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: commonpool@protonmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: commonpool-cert-key
    solvers:
    - selector:
        dnsZones:
          - "commonpool.net"
          - "*.commonpool.net"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z099637722IJL00LBV98X
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: commonpool-cert-prod
  namespace: istio-system
spec:
  secretName: commonpool-cert-prod
  dnsNames:
  - commonpool.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-cert-prod
  namespace: istio-system
spec:
  secretName: keycloak-cert-prod
  dnsNames:
  - auth.commonpool.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer