apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: commonpool
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - commonpool.net
    - "*.commonpool.net"
    tls:
      httpsRedirect: true 
  - port:
      number: 443
      name: https-443
      protocol: HTTPS
    hosts:
    - commonpool.net
    - "*.commonpool.net"
    tls:
      mode: SIMPLE 
      credentialName: commonpool-cert-prod
  - port:
      number: 7474
      name: neo4j-https
      protocol: HTTPS
    hosts:
      - "*.graphdb.commonpool.net"
      - "graphdb.commonpool.net"
    tls:
      mode: SIMPLE
      credentialName: commonpool-cert-prod
  - port:
      number: 7687
      name: neo4j-bolt
      protocol: HTTPS
    hosts:
      - "0.graphdb.commonpool.net"
      - "1.graphdb.commonpool.net"
      - "2.graphdb.commonpool.net"
      - "graphdb.commonpool.net"
    tls:
      mode: SIMPLE
      credentialName: commonpool-cert-prod
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: commonpool
  namespace: default
spec:
  hosts:
  - commonpool.net
  gateways:
  - commonpool
  http:
  - name: "prod-backend"
    match:
    - uri:
        prefix: "/api"
    route:
    - destination:
        host: staging-backend
        subset: staging
  - name: "prod-frontend"
    route:
    - destination:
        host: staging-frontend
        subset: staging
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: staging-backend
spec:
  host: staging-backend.default.svc.cluster.local
  subsets:
  - name: staging
    labels:
      version: staging
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: staging-frontend
spec:
  host: staging-frontend.default.svc.cluster.local
  subsets:
  - name: staging
    labels:
      version: staging
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: neo4j-0
  namespace: default
spec:
  gateways:
    - commonpool
  hosts:
    - graphdb-neo4j-core-0.graphdb-neo4j.default.svc.cluster.local
    - 0.graphdb.commonpool.net
  http:
    - match:
        - port: 7687
      route:
        - destination:
            host: graphdb-neo4j-0.default.svc.cluster.local
            port:
              number: 7687
    - match:
        - port: 7474
      route:
        - destination:
            host: graphdb-neo4j-0.default.svc.cluster.local
            port:
              number: 7474
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: neo4j-1
  namespace: default
spec:
  gateways:
    - commonpool
  hosts:
    - graphdb-neo4j-core-1.graphdb-neo4j.default.svc.cluster.local
    - 1.graphdb.commonpool.net
  http:
    - match:
        - port: 7687
      route:
        - destination:
            host: graphdb-neo4j-1.default.svc.cluster.local
            port:
              number: 7687
    - match:
        - port: 7474
      route:
        - destination:
            host: graphdb-neo4j-1.default.svc.cluster.local
            port:
              number: 7474
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: neo4j-2
  namespace: default
spec:
  gateways:
    - commonpool
  hosts:
    - graphdb-neo4j-core-2.graphdb-neo4j.default.svc.cluster.local
    - 2.graphdb.commonpool.net
  http:
    - match:
        - port: 7687
      route:
        - destination:
            host: graphdb-neo4j-2.default.svc.cluster.local
            port:
              number: 7687
    - match:
        - port: 7474
      route:
        - destination:
            host: graphdb-neo4j-2.default.svc.cluster.local
            port:
              number: 7474
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: neo4j
  namespace: default
spec:
  gateways:
    - commonpool
  hosts:
    - graphdb-neo4j.default.svc.cluster.local
    - graphdb.commonpool.net
  http:
    - match:
        - port: 7687
      route:
        - destination:
            host: graphdb-neo4j.default.svc.cluster.local
            port:
              number: 7687
    - match:
        - port: 7474
      route:
        - destination:
            host: graphdb-neo4j.default.svc.cluster.local
            port:
              number: 7474
---