apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: commonpool-cert-prod
  namespace: istio-system
spec:
  secretName: commonpool-cert-prod
  dnsNames:
    - commonpool.net
    - "*.commonpool.net"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer