apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: commonpool-cert-prod
  namespace: istio-system
spec:
  secretName: commonpool-cert-prod
  dnsNames:
    - commonpool.dev
    - "*.commonpool.dev"
    - "*.graphdb.commonpool.dev"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer