apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: commonpool
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 5432
        name: postgres-tcp
        protocol: TCP
      hosts:
        - "db.commonpool.dev"
    - port:
        number: 5672
        name: amqp-tcp
        protocol: TCP
      hosts:
        - "amqp.commonpool.dev"
    - port:
        number: 443
        name: rabbit-tls
        protocol: HTTPS
      hosts:
        - rabbit.commonpool.dev
      tls:
        mode: SIMPLE
        credentialName: commonpool-cert-prod
    - port:
        number: 6379
        name: redis-tls
        protocol: TLS
      hosts:
        - redis.commonpool.dev
      tls:
        mode: SIMPLE
        credentialName: commonpool-cert-prod
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: postgres
spec:
  hosts:
    - postgres.default.svc.cluster.local
    - db.commonpool.dev
  gateways:
    - commonpool
  tcp:
    - match:
        - port: 5432
      route:
        - destination:
            host: postgres.default.svc.cluster.local
            port:
              number: 5432
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: amqp
spec:
  hosts:
    - amqp.default.svc.cluster.local
    - amqp.commonpool.dev
  gateways:
    - commonpool
  tcp:
    - match:
        - port: 5672
      route:
        - destination:
            host: rabbit.default.svc.cluster.local
            port:
              number: 5672
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rabbitmq
spec:
  hosts:
    - rabbit.default.svc.cluster.local
    - rabbit.commonpool.dev
  gateways:
    - commonpool
  http:
    - route:
        - destination:
            host: rabbit.default.svc.cluster.local
            port:
              number: 15672
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: redis
spec:
  hosts:
    - redis-master.default.svc.cluster.local
    - redis.commonpool.dev
  gateways:
    - commonpool
  tcp:
    - match:
        - port: 6379
      route:
        - destination:
            host: redis-master.default.svc.cluster.local
            port:
              number: 6379