// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/resources": {
            "get": {
                "description": "Search for resources",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Searches resources",
                "operationId": "searchResources",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search text",
                        "name": "query",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "0",
                            "1"
                        ],
                        "type": "string",
                        "description": "Resource type",
                        "name": "type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Number of resources to take",
                        "name": "take",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Number of resources to skip",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.SearchResourcesResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates a resource",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Updates a resource",
                "operationId": "updateResource",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Resource id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Resource to create",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.UpdateResourceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.UpdateResourceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a resource",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Creates a resource",
                "operationId": "createResource",
                "parameters": [
                    {
                        "description": "Resource to create",
                        "name": "resource",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.CreateResourceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.CreateResourceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    }
                }
            }
        },
        "/resources/:id": {
            "get": {
                "description": "Gets a resource by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "resources"
                ],
                "summary": "Gets a single resource",
                "operationId": "getResource",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Resource id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.GetResourceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "utils.Error": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "web.CreateResourcePayload": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "exchangeValue": {
                    "type": "integer"
                },
                "necessityLevel": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "timeSensitivity": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "web.CreateResourceRequest": {
            "type": "object",
            "properties": {
                "resource": {
                    "type": "object",
                    "$ref": "#/definitions/web.CreateResourcePayload"
                }
            }
        },
        "web.CreateResourceResponse": {
            "type": "object",
            "properties": {
                "resource": {
                    "type": "object",
                    "$ref": "#/definitions/web.Resource"
                }
            }
        },
        "web.GetResourceResponse": {
            "type": "object",
            "properties": {
                "resource": {
                    "type": "object",
                    "$ref": "#/definitions/web.Resource"
                }
            }
        },
        "web.Resource": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "exchangeValue": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "necessityLevel": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "timeSensitivity": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "web.SearchResourcesResponse": {
            "type": "object",
            "properties": {
                "resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.Resource"
                    }
                },
                "skip": {
                    "type": "integer"
                },
                "take": {
                    "type": "integer"
                },
                "totalCount": {
                    "type": "integer"
                }
            }
        },
        "web.UpdateResourcePayload": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "exchangeValue": {
                    "type": "integer"
                },
                "necessityLevel": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                },
                "timeSensitivity": {
                    "type": "integer"
                },
                "type": {
                    "type": "integer"
                }
            }
        },
        "web.UpdateResourceRequest": {
            "type": "object",
            "properties": {
                "resource": {
                    "type": "object",
                    "$ref": "#/definitions/web.UpdateResourcePayload"
                }
            }
        },
        "web.UpdateResourceResponse": {
            "type": "object",
            "properties": {
                "resource": {
                    "type": "object",
                    "$ref": "#/definitions/web.Resource"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "127.0.0.1:8585",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "resources api",
	Description: "resources api",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
